/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type FragranceType = {
  _id: string;
  _type: "fragranceType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  course?: string;
  title?: string;
  brand?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  linkImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  courseImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  courseText?: BlockContent;
  intro?: BlockContent;
  videoFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  posterImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  info?: BlockContent;
  productText?: BlockContent;
  products?: Array<
    {
      _key: string;
    } & Product
  >;
  bottomText?: string;
  orderRank?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote" | "small";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
  | {
      id?: string;
      _type: "break";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Product = {
  _type: "product";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  size?: string;
  link?: string;
};

export type TextImageBlock = {
  _type: "textImageBlock";
  heading?: BlockContent;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  ctaBlock?: Array<{
    text?: string;
    link?: string;
    _key: string;
  }>;
  imageLeft?: boolean;
};

export type ImageBlock = {
  _type: "imageBlock";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  text?: BlockContent;
};

export type HeadingText = {
  _type: "headingText";
  heading?: BlockContent;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeadingText)
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & TextImageBlock)
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | FragranceType
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Product
  | TextImageBlock
  | ImageBlock
  | HeadingText
  | Home
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: HOME_QUERY
// Query: *[_type == "home"][0]{    _id,    pageBuilder[]{      _type == "headingText" => {        _type,        heading,        image{          alt,          asset->        }      },      _type == "imageBlock" => {        _type,        image{          alt,          asset->        },        text      },      _type == "textImageBlock" => {        _type,        heading,        image{          alt,          asset->        },        ctaBlock[]{          text,          link        },        imageLeft      }    }  }
export type HOME_QUERYResult = {
  _id: string;
  pageBuilder: Array<
    | {
        _type: "headingText";
        heading: BlockContent | null;
        image: {
          alt: string | null;
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
        } | null;
      }
    | {
        _type: "imageBlock";
        image: {
          alt: string | null;
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
        } | null;
        text: BlockContent | null;
      }
    | {
        _type: "textImageBlock";
        heading: BlockContent | null;
        image: {
          alt: string | null;
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
        } | null;
        ctaBlock: Array<{
          text: string | null;
          link: string | null;
        }> | null;
        imageLeft: boolean | null;
      }
  > | null;
} | null;
// Variable: FRAGRANCE_QUERY
// Query: *[_type == "fragranceType" && slug.current == $slug][0]{    _id,    title,    brand,    course,    slug,    orderRank,    mainImage{      alt,      asset->{        _id,        url,        metadata { dimensions { width, height, aspectRatio } }      }    },    linkImage{      alt,      asset->{        _id,        url,        metadata { dimensions { width, height, aspectRatio } }      }    },    courseImage{      alt,      asset->{        _id,        url,        metadata { dimensions { width, height, aspectRatio } }      }    },    videoFile{      asset->{        _id,        url,        metadata { dimensions { width, height, aspectRatio } }      }    },    posterImage{      asset->{        _id,        url,        metadata { dimensions { width, height, aspectRatio } }      }    },    courseText,    intro,    info,    productText,    bottomText,    products[]{      _key,      size,      link,      image{        alt,        asset->{          _id,          url,          metadata { dimensions { width, height, aspectRatio } }        }      }    }  }
export type FRAGRANCE_QUERYResult = {
  _id: string;
  title: string | null;
  brand: string | null;
  course: string | null;
  slug: Slug | null;
  orderRank: string | null;
  mainImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  linkImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  courseImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  videoFile: {
    asset: {
      _id: string;
      url: string | null;
      metadata: null;
    } | null;
  } | null;
  posterImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  courseText: BlockContent | null;
  intro: BlockContent | null;
  info: BlockContent | null;
  productText: BlockContent | null;
  bottomText: string | null;
  products: Array<{
    _key: string;
    size: string | null;
    link: string | null;
    image: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  }> | null;
} | null;
// Variable: FRAGRANCES_QUERY
// Query: *[_type == "fragranceType" && defined(slug.current)] | order(orderRank) {    _id,    title,    brand,    course,    slug,    mainImage{      alt,      asset->{        _id,        url,        metadata { dimensions { width, height, aspectRatio } }      }    },    courseImage{      alt,      asset->{        _id,        url,        metadata { dimensions { width, height, aspectRatio } }      }    },  }
export type FRAGRANCES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  brand: string | null;
  course: string | null;
  slug: Slug | null;
  mainImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  courseImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "home"][0]{\n    _id,\n    pageBuilder[]{\n      _type == "headingText" => {\n        _type,\n        heading,\n        image{\n          alt,\n          asset->\n        }\n      },\n\n      _type == "imageBlock" => {\n        _type,\n        image{\n          alt,\n          asset->\n        },\n        text\n      },\n\n      _type == "textImageBlock" => {\n        _type,\n        heading,\n        image{\n          alt,\n          asset->\n        },\n        ctaBlock[]{\n          text,\n          link\n        },\n        imageLeft\n      }\n    }\n  }\n': HOME_QUERYResult;
    '\n  *[_type == "fragranceType" && slug.current == $slug][0]{\n    _id,\n    title,\n    brand,\n    course,\n    slug,\n    orderRank,\n\n    mainImage{\n      alt,\n      asset->{\n        _id,\n        url,\n        metadata { dimensions { width, height, aspectRatio } }\n      }\n    },\n\n    linkImage{\n      alt,\n      asset->{\n        _id,\n        url,\n        metadata { dimensions { width, height, aspectRatio } }\n      }\n    },\n\n    courseImage{\n      alt,\n      asset->{\n        _id,\n        url,\n        metadata { dimensions { width, height, aspectRatio } }\n      }\n    },\n\n    videoFile{\n      asset->{\n        _id,\n        url,\n        metadata { dimensions { width, height, aspectRatio } }\n      }\n    },\n\n    posterImage{\n      asset->{\n        _id,\n        url,\n        metadata { dimensions { width, height, aspectRatio } }\n      }\n    },\n\n    courseText,\n    intro,\n    info,\n    productText,\n    bottomText,\n\n    products[]{\n      _key,\n      size,\n      link,\n      image{\n        alt,\n        asset->{\n          _id,\n          url,\n          metadata { dimensions { width, height, aspectRatio } }\n        }\n      }\n    }\n  }\n': FRAGRANCE_QUERYResult;
    '\n  *[_type == "fragranceType" && defined(slug.current)] | order(orderRank) {\n    _id,\n    title,\n    brand,\n    course,\n    slug,\n    mainImage{\n      alt,\n      asset->{\n        _id,\n        url,\n        metadata { dimensions { width, height, aspectRatio } }\n      }\n    },\n\n    courseImage{\n      alt,\n      asset->{\n        _id,\n        url,\n        metadata { dimensions { width, height, aspectRatio } }\n      }\n    },\n  }\n': FRAGRANCES_QUERYResult;
  }
}
